Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -66,9 +66,9 @@ jobs:
         export PATH=$HOME/.bun/bin:$PATH
         echo "Restarting React application with PM2..."
         # Delete the existing process if it exists
-        pm2 delete kwickbill-ui-main || echo "Process kwickbill-ui-main not found, skipping delete step."
+        pm2 delete kwickbill-ui-prod || echo "Process kwickbill-ui-prod not found, skipping delete step."
         # Start or restart the application
-        pm2 start serve --name kwickbill-ui-main -- -s dist -l 5173 || pm2 restart kwickbill-ui-main --update-env
+        pm2 start serve --name kwickbill-ui-prod -- -s dist -l 5173 || pm2 restart kwickbill-ui-prod --update-env
         # Save the PM2 process list
         pm2 save
         # List all PM2 processes
