Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -65,10 +65,11 @@ jobs:
       run: |
         export PATH=$HOME/.bun/bin:$PATH
         echo "Restarting React application with PM2..."
-        # Start or restart kwickbill-ui-dev
-        pm2 delete kwickbill-ui-dev
+        # Delete the existing process if it exists
+        pm2 delete kwickbill-ui-dev || echo "Process kwickbill-ui-dev not found, skipping delete step."
+        # Start or restart the application
         pm2 start serve --name kwickbill-ui-dev -- -s dist -l 5177 || pm2 restart kwickbill-ui-dev --update-env
         # Save the PM2 process list
         pm2 save
         # List all PM2 processes
-        pm2 list 
+        pm2 list
